Add ci config for publishing docker image
poanetwork/tokenbridge-contracts pull request #473
Opened 2020-08-18 14:11 UTC by k1rill-fedoseev

This PR adds a GitHub Actions workflows for building and pushing docker images as described in #349

2020-08-19 14:53 UTC, akolotov requested changes

2020-08-19 14:53 UTC, akolotov commented on .github/workflows/publish-docker-image-on-tags.yml
> +          repository: ${{ secrets.DOCKER_USERNAME }}/tokenbridge-contracts
```suggestion
          repository: poanetwork/tokenbridge-contracts
```

2020-08-19 14:53 UTC, akolotov commented on .github/workflows/publish-docker-image-on-branch.yml
> +          repository: ${{ secrets.DOCKER_USERNAME }}/tokenbridge-contracts
```suggestion
          repository: poanetwork/tokenbridge-contracts
```

2020-08-19 14:56 UTC, akolotov reviewed
Will the images be built and published only in case if other jobs are successful?

2020-08-20 06:19 UTC, k1rill-fedoseev commented
Initially, it was not so.
But now I have found a workaround how to place everything in a single workflow. So everything should work as expected.

2020-08-20 09:14 UTC, akolotov approved these changes
Ok. Let's try

2020-08-20 09:14 UTC, merged