Add GSN support for erc_to_erc bridge mode
poanetwork/tokenbridge-contracts pull request #571
Opened 2021-01-15 13:43 UTC by LyzeOfKiel

Implementation of token paymaster contract for GSN, added modified version of `executeSignatures` which interacts with paymaster.
**NOTE**: Before starting tests don't forget to start GSN on a local test network via `npx gsn start`.
**ISSUES**: There are two hard-coded constants in the paymaster contract related to its gas consumption. We need to find a way to make them more precise or remove them at all.

2021-01-18 10:06 UTC, k1rill-fedoseev requested changes

2021-01-19 17:31 UTC, LyzeOfKiel commented on contracts/upgradeable_contracts/erc20_to_erc20/GSNForeignBridgeErcToErc.sol
> +            require(erc20token().transfer(addressStorage[PAYMASTER], unshiftMaxFee), "paymaster tranfer failed");
For now I don't see a way to do this. When forwarder calls the target contract it only provides actual function parameters and the address of the message sender (https://github.com/opengsn/gsn/blob/master/contracts/forwarder/Forwarder.sol#L63).

2021-01-20 17:19 UTC, LyzeOfKiel commented on contracts/gsn/token_paymaster/TokenPaymaster.sol
> +    ) public returns (bytes memory context, bool revertOnRecipientRevert) {
Fixed

2021-01-20 17:20 UTC, LyzeOfKiel commented on contracts/gsn/token_paymaster/TokenPaymaster.sol
> +        return (abi.encode(relayRequest.request.from), false);
Fixed

2021-01-20 17:21 UTC, LyzeOfKiel commented on contracts/gsn/token_paymaster/TokenPaymaster.sol
> +        uint256 tokenBalanceBefore = erc20().balanceOf(address(this));
Yes, now I pass `maxTokensFee` to `postRelayedCall` via `context`

2021-01-20 17:22 UTC, LyzeOfKiel commented on contracts/gsn/token_paymaster/TokenPaymaster.sol
> +        uint256 tokensLeft = erc20().balanceOf(address(this));
Fixed

2021-01-20 17:22 UTC, LyzeOfKiel commented on contracts/gsn/token_paymaster/TokenPaymaster.sol
> +        require(erc20().transfer(to, tokensLeft));
Agree

2021-01-20 17:24 UTC, LyzeOfKiel commented on contracts/mocks/UniswapRouterMock.sol
> +        TokenPaymaster(msg.sender).deposit.value(ethToSend)();
Done

2021-01-20 17:26 UTC, LyzeOfKiel commented on contracts/upgradeable_contracts/erc20_to_erc20/GSNForeignBridgeErcToErc.sol
> +        trustedForwarder = _trustedForwarder;
Had to change `BaseRelayRecipient` structure a little for this

2021-01-20 17:26 UTC, LyzeOfKiel commented on test/erc_to_erc/gsn/gsn.test.js
> +    it('should allow to executeSignaturesGSN', async () => {
Done

2021-01-20 17:27 UTC, LyzeOfKiel commented on contracts/gsn/token_paymaster/TokenPaymaster.sol
> +        return (abi.encode(relayRequest.request.from), false);
Fixed

2021-01-20 17:27 UTC, LyzeOfKiel commented on contracts/gsn/token_paymaster/TokenPaymaster.sol
> +        setTrustedForwarder(IForwarder(fw));
Done

2021-01-21 18:05 UTC, k1rill-fedoseev commented on test/erc_to_native/foreign_bridge_gsn.test.js
> +contract('ForeignBridge_ERC20_to_ERC20_GSN', async accounts => {
```suggestion
contract('ForeignBridge_ERC20_to_Native_GSN', async accounts => {
```

2021-05-06 20:03 UTC, k1rill-fedoseev commented on contracts/gsn/token_paymaster/TokenPaymaster.sol
> +        require(bridge == relayRequest.request.to, "accepets only bridge calls");
```suggestion
        require(bridge == relayRequest.request.to, "accepts only bridge calls");
```

2021-05-06 20:11 UTC, LyzeOfKiel commented on scripts/test.sh
> +#!/usr/bin/env bash
Forgot to drop it after rebase

2021-05-06 20:13 UTC, k1rill-fedoseev approved these changes

2021-05-06 20:31 UTC, merged